### ISSUE TITLE
No way to stop running test

### ISSUE THREAD

**Issue by honzakadlec** [uilicious/uilicious-cli#3]
There is no way to stop UiLic tests started from CLI

**Comment by PicoCreator** [comment]
For clarification, are you refering to the test continuing running, even after "termination" is done on command line? : We could add a stop signal to be sent to the server in this case.

Or is the command line not exiting when attempted?

**Comment by honzakadlec** [comment]
Hi @PicoCreator yes, ideally to sending signal to running executable to stop the remote testrun..

**Comment by honzakadlec** [comment]
Hi @PicoCreator, any news on this please? Thank you in advance

**Comment by douglascayers** [comment]
Either that running test on UIlicious stops when the local CLI process is stopped/killed, or that there's a new CLI command for stopping a test run by being given a Test Run ID. Thanks

**Comment by PicoCreator** [comment]
This is implemented in the current build - after a major overhaul on how the CLI was implemented.

https://github.com/uilicious/uilicious-cli/releases/tag/v5.1.2

You can now interrupt tests if it has started. Note that you should only do the "Ctrl-C" once, as doing "Ctrl-C" twice will do an immediate termination (where the cleanup process is ignored)
