### ISSUE TITLE
internal implementation uses V8 ?

### ISSUE THREAD

**Issue by honzakadlec** [uilicious/uilicious-cli#4]
Just seen this warning :
(node:19689) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

It's running nodeJS inside GoLang executable? Oh my dear, WHY?

Go is so much more efficient in writing this type of apps, why not to use it if it's client-server architecture?

**Comment by PicoCreator** [comment]
While I agree in large parts - we only have 1 dev on staff who is able to maintain go projects.
So we made the switched to v8 to prioritize overall maintainability of the project sadly =(

We may reconsider when we scale up in the future (I really do not like our memory usage)

(Apologies for late response, we generally respond via helpdesk, and I missed the notifications here)
