### ISSUE TITLE
JS error stop cloud test execution, but does not emmit the error on client side, does not stop the execution

### ISSUE THREAD

**Issue by honzakadlec** [uilicious/uilicious-cli#5]
UiLic test is stopped due to JS error:
![image](https://user-images.githubusercontent.com/13018181/96720892-aac05980-13ab-11eb-83e2-8cc9cd61c6e6.png)

uilic cli is not stopped and is stucked forever:
2020-10-21 11:23:49 [Step 171 - failure]: I see "Thank you callum!" - 15.774
2020-10-21 11:23:49 [Step 172 - failure]: I get text from ".os-order-number" - 0.022

**Comment by douglascayers** [comment]
Agree, I think that this is a bug with the CLI that it doesn't abort or show error info when the remote test fails. I've been killing my CLI processes manually, but that doesn't work well in a fully automated environment.

**Comment by PicoCreator** [comment]
This is now fixed in the latest build found here : 

https://github.com/uilicious/uilicious-cli/releases/tag/v5.1.2

Hope it helps =) Thanks for raising the issue
