### ISSUE TITLE
No output or Segmentation fault (on windows)

### ISSUE THREAD

**Issue by vectorkovacspeter** [uilicious/uilicious-cli#7]
Hello,

after a freash install via npm on windows, with v16.3.0

For the command uilicious-cli --help I have no output, just get the promt back.

In Git Bash commendline I get 'Segmentation fault' message

**Comment by PicoCreator** [comment]
Please update to the current version, we have switched away from the go build, to resolve some of these common issues on NPM.

If you are using the binary build : For windows, please use powershell instead of the cmd terminal to avoid common formatting issues
